import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:project/ads/interstitial_ad_helper.dart';
import 'package:project/database/test_history_db.dart';

class TestQuestionPage extends StatefulWidget {
  final String testType;
  final String testLabel;

  const TestQuestionPage({super.key, required this.testType, required this.testLabel});

  @override
  State<TestQuestionPage> createState() => _TestQuestionPageState();
}

class _TestQuestionPageState extends State<TestQuestionPage> {
  int currentIndex = 0;
  int score = 0;

  late List<String> questions;

  final Map<String, List<String>> testQuestions = {
  'depression': [
    'Saya merasa sedih hampir setiap hari.',
    'Saya kehilangan minat terhadap hal-hal yang dulu saya sukai.',
    'Saya merasa kelelahan tanpa alasan yang jelas.',
    'Saya merasa tidak berharga atau bersalah.',
    'Saya sulit tidur atau terlalu banyak tidur.',
    'Saya kehilangan nafsu makan atau makan berlebihan.',
    'Saya sulit berkonsentrasi.',
    'Saya merasa lamban dalam berpikir atau bergerak.',
    'Saya berpikir lebih baik mati atau melukai diri sendiri.',
    'Saya kehilangan motivasi untuk beraktivitas.',
    'Saya merasa hampa atau kosong.',
    'Saya menangis tanpa alasan yang jelas.',
    'Saya menghindari interaksi sosial.',
    'Saya sulit menikmati kebahagiaan.',
    'Saya merasa masa depan suram.',
    'Saya tidak memiliki energi untuk melakukan hal-hal kecil.',
    'Saya kehilangan minat terhadap pekerjaan atau sekolah.',
    'Saya merasa sulit untuk memulai sesuatu.',
    'Saya sering merasa cemas tanpa alasan.',
    'Saya merasa tidak mampu mengendalikan emosi saya.',
  ],
  'anxiety': [
    'Saya merasa tegang atau gelisah.',
    'Saya sulit mengontrol rasa khawatir.',
    'Saya merasa sesuatu yang buruk akan terjadi.',
    'Saya sulit santai atau tenang.',
    'Saya takut berada di tempat ramai.',
    'Saya mengalami jantung berdebar tanpa alasan.',
    'Saya merasa ingin lari dari situasi tertentu.',
    'Saya mudah panik.',
    'Saya sering memikirkan hal buruk yang belum tentu terjadi.',
    'Saya sulit tidur karena cemas.',
    'Saya merasa tidak aman.',
    'Saya terlalu khawatir tentang pendapat orang lain.',
    'Saya takut kehilangan kendali.',
    'Saya sulit fokus karena cemas.',
    'Saya takut membuat kesalahan kecil.',
    'Saya mudah terkejut.',
    'Saya merasa ingin menarik diri dari lingkungan.',
    'Saya merasa lelah karena terlalu khawatir.',
    'Saya sulit bernapas ketika cemas.',
    'Saya sulit menenangkan diri sendiri.',
  ],
  'bipolar': [
    'Saya merasa sangat bersemangat tanpa alasan.',
    'Saya berbicara sangat cepat.',
    'Saya tidur sedikit tetapi tetap berenergi.',
    'Saya memiliki banyak ide sekaligus.',
    'Saya merasa sangat percaya diri.',
    'Saya membuat keputusan impulsif.',
    'Saya mengeluarkan uang tanpa pertimbangan.',
    'Saya merasa tidak bisa berhenti bicara.',
    'Saya mudah tersinggung tanpa sebab.',
    'Saya tiba-tiba kehilangan energi.',
    'Saya merasa sangat sedih setelah merasa sangat senang.',
    'Saya sulit menjaga hubungan sosial.',
    'Saya merasa suasana hati berubah cepat.',
    'Saya merasa sulit dikendalikan.',
    'Saya sulit tidur saat merasa gembira berlebihan.',
    'Saya berbicara terlalu banyak tanpa jeda.',
    'Saya merasa mudah marah tanpa alasan jelas.',
    'Saya merasa kehidupan saya seperti naik turun ekstrem.',
    'Saya merasa tidak stabil secara emosi.',
    'Saya sering melakukan hal yang saya sesali kemudian.',
  ],
  'ptsd': [
    'Saya sering mengingat kejadian traumatis di masa lalu.',
    'Saya mengalami mimpi buruk berulang.',
    'Saya menghindari tempat atau orang yang mengingatkan kejadian itu.',
    'Saya sulit tidur karena trauma.',
    'Saya merasa selalu waspada terhadap bahaya.',
    'Saya mudah kaget oleh suara keras.',
    'Saya merasa mati rasa secara emosional.',
    'Saya merasa bersalah terhadap kejadian masa lalu.',
    'Saya sulit mempercayai orang lain.',
    'Saya merasa terasing dari orang sekitar.',
    'Saya menghindari pembicaraan tentang kejadian itu.',
    'Saya merasa takut tanpa sebab.',
    'Saya mudah marah atau tersinggung.',
    'Saya merasa kehilangan minat pada aktivitas yang disukai.',
    'Saya sulit menikmati kebahagiaan.',
    'Saya merasa tidak aman bahkan di tempat yang aman.',
    'Saya merasa hidup tidak berarti.',
    'Saya mengalami kilas balik kejadian traumatis.',
    'Saya sulit fokus saat bekerja.',
    'Saya merasa tidak akan pernah pulih sepenuhnya.',
  ],
  'addiction': [
    'Saya sulit berhenti menggunakan sesuatu meskipun tahu risikonya.',
    'Saya merasa tidak bisa hidup tanpa hal itu.',
    'Saya menyembunyikan kebiasaan ini dari orang lain.',
    'Saya kehilangan waktu karena kebiasaan tersebut.',
    'Saya sering merasa bersalah setelah melakukannya.',
    'Saya mencoba berhenti tapi selalu gagal.',
    'Saya merasa cemas jika tidak melakukannya.',
    'Saya mengabaikan tanggung jawab karena kebiasaan ini.',
    'Saya merasa kebiasaan ini mengendalikan saya.',
    'Saya kehilangan minat pada hal-hal lain.',
    'Saya rela mengorbankan uang demi hal itu.',
    'Saya merasa lelah tapi tidak bisa berhenti.',
    'Saya berbohong untuk menutupi kebiasaan ini.',
    'Saya merasa kosong jika tidak melakukannya.',
    'Saya sering kembali melakukannya setelah berjanji berhenti.',
    'Saya merasa kehilangan kendali diri.',
    'Saya sering merasa tidak bahagia tanpa hal itu.',
    'Saya tahu ini buruk tapi tetap melakukannya.',
    'Saya takut kehilangan akses terhadap hal itu.',
    'Saya merasa tidak bisa berhenti sendirian.',
  ],
  'adhd': [
    'Saya sulit fokus dalam waktu lama.',
    'Saya sering berpindah aktivitas tanpa menyelesaikannya.',
    'Saya mudah teralihkan oleh hal kecil.',
    'Saya sering lupa janji atau tugas.',
    'Saya sulit mengatur waktu dengan baik.',
    'Saya mudah bosan.',
    'Saya sulit duduk diam lama.',
    'Saya berbicara sebelum berpikir.',
    'Saya sering kehilangan barang penting.',
    'Saya merasa selalu gelisah.',
    'Saya sulit mengikuti instruksi panjang.',
    'Saya sering menunda pekerjaan.',
    'Saya sulit mendengarkan sampai selesai.',
    'Saya sering melakukan kesalahan kecil karena kurang fokus.',
    'Saya sulit tidur karena pikiran aktif.',
    'Saya sering impulsif dalam mengambil keputusan.',
    'Saya sulit menyelesaikan tugas panjang.',
    'Saya merasa frustrasi karena tidak bisa fokus.',
    'Saya sering lupa hal-hal sederhana.',
    'Saya mudah terganggu oleh suara sekitar.',
  ],
  'stress': [
    'Saya merasa kelelahan secara mental.',
    'Saya merasa sulit menenangkan diri.',
    'Saya sering merasa tegang.',
    'Saya sulit tidur karena pikiran penuh.',
    'Saya mudah marah tanpa alasan.',
    'Saya merasa tidak punya waktu untuk diri sendiri.',
    'Saya kehilangan motivasi.',
    'Saya merasa terlalu banyak tekanan.',
    'Saya sulit fokus karena pikiran bercabang.',
    'Saya merasa hidup tidak seimbang.',
    'Saya sering merasa cemas tanpa sebab.',
    'Saya merasa terjebak dalam rutinitas.',
    'Saya merasa tidak ada yang memahami saya.',
    'Saya merasa tubuh saya kaku dan tegang.',
    'Saya sulit menikmati hal-hal kecil.',
    'Saya sering lupa makan atau istirahat.',
    'Saya merasa mudah lelah bahkan tanpa aktivitas berat.',
    'Saya merasa ingin menyerah.',
    'Saya merasa kehilangan arah.',
    'Saya sulit berpikir jernih di bawah tekanan.',
  ],
  'sleep': [
    'Saya sulit tidur di malam hari.',
    'Saya sering terbangun di tengah malam.',
    'Saya tidur terlalu sedikit.',
    'Saya tidur terlalu lama.',
    'Saya merasa tidak segar setelah bangun tidur.',
    'Saya sulit tidur tanpa bantuan tertentu.',
    'Saya merasa mengantuk di siang hari.',
    'Saya sulit menenangkan pikiran sebelum tidur.',
    'Saya memiliki jadwal tidur tidak teratur.',
    'Saya sering terbangun karena mimpi buruk.',
    'Saya sulit tidur di tempat baru.',
    'Saya merasa stres saat waktu tidur tiba.',
    'Saya sering melihat layar sebelum tidur.',
    'Saya bangun terlalu pagi tanpa sebab.',
    'Saya merasa tubuh saya berat setelah tidur.',
    'Saya sering menunda waktu tidur.',
    'Saya sering tidur di waktu yang tidak tepat.',
    'Saya sulit tidur jika ada cahaya atau suara.',
    'Saya sering mengganti posisi tidur.',
    'Saya merasa kualitas tidur saya buruk.',
  ],
  'selfesteem': [
    'Saya merasa percaya diri dengan diri saya sendiri.',
    'Saya sering membandingkan diri saya dengan orang lain.',
    'Saya merasa tidak cukup baik.',
    'Saya menghargai diri saya apa adanya.',
    'Saya merasa tidak layak untuk sukses.',
    'Saya bangga dengan pencapaian saya.',
    'Saya sulit menerima pujian.',
    'Saya sering merasa gagal.',
    'Saya merasa tidak menarik.',
    'Saya yakin bisa mencapai tujuan saya.',
    'Saya merasa malu dengan diri sendiri.',
    'Saya merasa tidak berarti bagi orang lain.',
    'Saya menerima kekurangan saya.',
    'Saya sering merasa rendah diri.',
    'Saya merasa pantas untuk dicintai.',
    'Saya sering berpikir negatif tentang diri saya.',
    'Saya merasa mampu menghadapi tantangan.',
    'Saya merasa tidak memiliki kelebihan.',
    'Saya bangga dengan siapa saya sekarang.',
    'Saya merasa tidak bisa membanggakan siapa pun.',
  ],
    'emotion': [
    'Saya mampu mengenali emosi saya sendiri dengan baik.',
    'Saya sering bereaksi berlebihan terhadap situasi kecil.',
    'Saya bisa tetap tenang dalam situasi sulit.',
    'Saya merasa emosi saya berubah dengan cepat.',
    'Saya memahami alasan di balik perasaan saya.',
    'Saya sulit mengendalikan amarah saya.',
    'Saya sering merasa bingung dengan perasaan saya sendiri.',
    'Saya mampu mengekspresikan emosi saya secara sehat.',
    'Saya mudah tersinggung oleh perkataan orang lain.',
    'Saya bisa memaafkan orang lain dengan tulus.',
    'Saya sering menyimpan emosi negatif terlalu lama.',
    'Saya dapat menenangkan diri ketika merasa marah.',
    'Saya mudah menangis ketika merasa stres.',
    'Saya mampu mengungkapkan perasaan tanpa menyakiti orang lain.',
    'Saya sering tidak tahu bagaimana perasaan saya sebenarnya.',
    'Saya merasa emosi saya sulit diprediksi.',
    'Saya mampu menenangkan orang lain yang sedang marah.',
    'Saya sering memendam emosi agar tidak menyakiti orang lain.',
    'Saya cepat bangkit setelah merasa kecewa.',
    'Saya merasa emosi saya seimbang setiap hari.',
  ],
  'anger': [
    'Saya mudah marah terhadap hal-hal kecil.',
    'Saya sering menyesali ucapan saat sedang marah.',
    'Saya bisa menahan diri saat sedang emosi.',
    'Saya sering membentak orang lain tanpa sadar.',
    'Saya merasa marah ketika sesuatu tidak sesuai rencana.',
    'Saya sulit memaafkan orang yang membuat saya kecewa.',
    'Saya mampu menenangkan diri setelah marah.',
    'Saya sering merasa tidak dihargai sehingga marah.',
    'Saya cenderung menyimpan kemarahan dalam hati.',
    'Saya bisa mengontrol nada suara saat emosi.',
    'Saya merasa sulit berpikir jernih ketika marah.',
    'Saya sering ingin membalas dendam.',
    'Saya cepat merasa tersinggung.',
    'Saya menggunakan kemarahan untuk memotivasi diri.',
    'Saya merasa malu setelah marah.',
    'Saya sering marah tanpa alasan jelas.',
    'Saya bisa membicarakan masalah tanpa emosi berlebihan.',
    'Saya cenderung menyalahkan orang lain saat emosi.',
    'Saya sering menyesali perilaku saya setelah marah.',
    'Saya mampu memaafkan orang lain dengan mudah.',
  ],
  'burnout': [
    'Saya merasa lelah secara emosional hampir setiap hari.',
    'Saya kehilangan semangat bekerja atau belajar.',
    'Saya merasa tidak lagi peduli terhadap hasil pekerjaan.',
    'Saya merasa terlalu banyak beban yang harus saya tanggung.',
    'Saya merasa sulit memulai aktivitas.',
    'Saya merasa tidak dihargai meski sudah berusaha keras.',
    'Saya merasa kewalahan oleh tanggung jawab.',
    'Saya merasa frustrasi terhadap pekerjaan saya.',
    'Saya merasa kosong dan kehilangan arah.',
    'Saya merasa tidak punya energi untuk berinteraksi.',
    'Saya merasa pekerjaan saya tidak berarti lagi.',
    'Saya merasa mudah sakit akhir-akhir ini.',
    'Saya ingin berhenti dari semua yang sedang saya lakukan.',
    'Saya merasa terjebak dalam rutinitas yang membosankan.',
    'Saya sulit bangun di pagi hari untuk bekerja.',
    'Saya kehilangan minat terhadap hal-hal yang dulu saya nikmati.',
    'Saya sering menunda pekerjaan karena lelah secara mental.',
    'Saya merasa performa saya menurun drastis.',
    'Saya merasa tidak ada waktu untuk diri sendiri.',
    'Saya merasa benar-benar kehabisan tenaga.',
  ],
  'social': [
    'Saya merasa gugup saat harus berbicara di depan orang banyak.',
    'Saya merasa canggung dalam situasi sosial.',
    'Saya takut dihakimi orang lain.',
    'Saya sulit memulai percakapan.',
    'Saya merasa khawatir tentang kesan orang terhadap saya.',
    'Saya menghindari acara sosial jika memungkinkan.',
    'Saya sering merasa diperhatikan secara negatif.',
    'Saya sulit berbicara dengan orang baru.',
    'Saya merasa tidak nyaman dalam kelompok besar.',
    'Saya sering khawatir mengatakan hal yang salah.',
    'Saya merasa tegang di lingkungan baru.',
    'Saya lebih suka menyendiri daripada berinteraksi.',
    'Saya sulit mempertahankan kontak mata saat berbicara.',
    'Saya sering menyiapkan kata-kata sebelum berbicara.',
    'Saya merasa orang lain menilai saya terus-menerus.',
    'Saya merasa tidak tahu apa yang harus dikatakan di situasi sosial.',
    'Saya sering menolak undangan karena takut canggung.',
    'Saya khawatir dianggap aneh oleh orang lain.',
    'Saya sulit bersikap santai di hadapan banyak orang.',
    'Saya merasa tidak cukup baik untuk diterima orang lain.',
  ],
  'focus': [
    'Saya sulit fokus dalam waktu lama.',
    'Saya sering kehilangan konsentrasi saat bekerja.',
    'Saya mudah terganggu oleh suara di sekitar.',
    'Saya sulit menyelesaikan tugas tanpa terdistraksi.',
    'Saya merasa pikiran saya melayang saat membaca.',
    'Saya sulit memusatkan perhatian pada satu hal.',
    'Saya sering menunda pekerjaan karena tidak fokus.',
    'Saya perlu waktu lama untuk kembali fokus.',
    'Saya sering membuka ponsel saat sedang bekerja.',
    'Saya mudah kehilangan motivasi di tengah tugas.',
    'Saya sulit mendengarkan orang lain dengan penuh perhatian.',
    'Saya mudah kehilangan arah dalam pembicaraan.',
    'Saya merasa otak saya lelah lebih cepat.',
    'Saya sering lupa detail kecil.',
    'Saya sulit fokus di tempat ramai.',
    'Saya merasa sulit menyelesaikan pekerjaan tepat waktu.',
    'Saya sering berpindah dari satu hal ke hal lain tanpa selesai.',
    'Saya merasa frustrasi karena kurang fokus.',
    'Saya membutuhkan waktu lama untuk memulai tugas.',
    'Saya sering membaca sesuatu berulang kali agar paham.',
  ],
  'memory': [
    'Saya sering lupa apa yang baru saja saya lakukan.',
    'Saya sulit mengingat nama orang baru.',
    'Saya sering lupa meletakkan barang.',
    'Saya sulit mengingat informasi penting.',
    'Saya merasa ingatan saya menurun.',
    'Saya sering lupa tanggal atau janji penting.',
    'Saya sulit mengingat hal-hal detail.',
    'Saya merasa perlu mencatat agar tidak lupa.',
    'Saya sering lupa hal kecil dalam percakapan.',
    'Saya sulit mengingat hal yang saya baca.',
    'Saya sering lupa arah jalan.',
    'Saya sulit mengingat apa yang saya pelajari kemarin.',
    'Saya merasa pikiran saya mudah kosong.',
    'Saya sering mengulangi hal yang sama tanpa sadar.',
    'Saya lupa alasan mengapa saya masuk ke ruangan tertentu.',
    'Saya sulit mengingat wajah seseorang.',
    'Saya sering lupa kata yang ingin saya ucapkan.',
    'Saya perlu waktu lama untuk mengingat sesuatu.',
    'Saya merasa mudah bingung ketika mengingat masa lalu.',
    'Saya sulit fokus karena ingatan saya kabur.',
  ],
  'energy': [
    'Saya merasa berenergi di pagi hari.',
    'Saya mudah merasa lelah di siang hari.',
    'Saya membutuhkan waktu lama untuk bersemangat.',
    'Saya merasa bugar sepanjang hari.',
    'Saya merasa lelah tanpa sebab jelas.',
    'Saya sering mengantuk saat beraktivitas.',
    'Saya memiliki motivasi tinggi setiap hari.',
    'Saya merasa kekurangan energi untuk berolahraga.',
    'Saya sering menunda pekerjaan karena kelelahan.',
    'Saya merasa aktif dan siap menghadapi tantangan.',
    'Saya cepat merasa kehabisan tenaga.',
    'Saya merasa tubuh saya berat saat bangun pagi.',
    'Saya bisa menjaga energi saya sepanjang hari.',
    'Saya sulit fokus karena kelelahan.',
    'Saya merasa energi saya menurun dari hari ke hari.',
    'Saya mudah merasa lelah setelah kegiatan ringan.',
    'Saya jarang merasa segar setelah tidur.',
    'Saya merasa tubuh saya penuh tenaga positif.',
    'Saya membutuhkan istirahat lebih lama dari biasanya.',
    'Saya merasa semangat saya menurun akhir-akhir ini.',
  ],
  'relationship': [
    'Saya merasa hubungan saya dengan orang lain sehat.',
    'Saya sering bertengkar dengan orang terdekat.',
    'Saya mampu berkomunikasi dengan baik dalam hubungan.',
    'Saya merasa tidak dimengerti oleh pasangan atau teman.',
    'Saya bisa mendengarkan orang lain dengan empati.',
    'Saya merasa hubungan saya tidak stabil.',
    'Saya mampu mengekspresikan kebutuhan saya dengan jujur.',
    'Saya sering merasa diabaikan dalam hubungan.',
    'Saya mampu memaafkan kesalahan orang lain.',
    'Saya sering merasa kesepian dalam hubungan.',
    'Saya merasa dihargai oleh orang sekitar.',
    'Saya merasa hubungan saya penuh tekanan.',
    'Saya terbuka untuk berdiskusi tanpa marah.',
    'Saya sering menarik diri saat ada masalah hubungan.',
    'Saya merasa hubungan saya saling mendukung.',
    'Saya sulit mempercayai orang lain sepenuhnya.',
    'Saya merasa hubungan saya membuat saya tumbuh.',
    'Saya sering merasa tidak aman dalam hubungan.',
    'Saya mampu menjaga batas sehat dalam hubungan.',
    'Saya merasa bahagia dengan hubungan yang saya miliki.',
  ],
  'productivity': [
    'Saya menyelesaikan tugas tepat waktu.',
    'Saya sering menunda pekerjaan tanpa alasan.',
    'Saya mampu mengatur prioritas dengan baik.',
    'Saya merasa produktivitas saya menurun.',
    'Saya bekerja dengan fokus tinggi.',
    'Saya sering kehilangan motivasi untuk bekerja.',
    'Saya mampu mengatur waktu secara efisien.',
    'Saya sering merasa tidak punya cukup waktu.',
    'Saya merasa puas dengan hasil kerja saya.',
    'Saya sering terdistraksi oleh hal kecil.',
    'Saya membuat rencana sebelum bekerja.',
    'Saya sering merasa tidak termotivasi.',
    'Saya mampu bekerja tanpa banyak gangguan.',
    'Saya sering menunda pekerjaan penting.',
    'Saya merasa mudah bosan saat bekerja.',
    'Saya menyelesaikan pekerjaan dengan hasil yang baik.',
    'Saya sulit fokus pada satu tugas.',
    'Saya merasa produktivitas saya konsisten.',
    'Saya sering multitasking tanpa hasil maksimal.',
    'Saya merasa bekerja lebih efektif akhir-akhir ini.',
  ],
  'mindfulness': [
    'Saya menyadari apa yang saya rasakan saat ini.',
    'Saya sering terburu-buru tanpa menikmati proses.',
    'Saya mampu fokus pada momen saat ini.',
    'Saya sering berpikir tentang masa lalu.',
    'Saya sulit menikmati waktu sekarang.',
    'Saya menyadari napas saya saat merasa stres.',
    'Saya sering khawatir tentang masa depan.',
    'Saya menyadari perubahan kecil dalam diri saya.',
    'Saya sering melakukan sesuatu tanpa sadar sepenuhnya.',
    'Saya mampu menghargai hal kecil dalam hidup.',
    'Saya sering merasa terjebak dalam pikiran negatif.',
    'Saya mampu mengamati emosi tanpa bereaksi berlebihan.',
    'Saya sering tergesa-gesa menyelesaikan sesuatu.',
    'Saya mampu menikmati setiap kegiatan kecil.',
    'Saya sadar ketika tubuh saya merasa tegang.',
    'Saya sering berpikir sambil melakukan hal lain.',
    'Saya mampu fokus penuh saat berbicara dengan orang lain.',
    'Saya menyadari lingkungan sekitar dengan tenang.',
    'Saya sering tidak sadar dengan apa yang saya rasakan.',
    'Saya merasa hadir sepenuhnya dalam aktivitas sehari-hari.',
  ]
  };

  @override
  void initState() {
    super.initState();
    InterstitialAdHelper.loadAd();
    questions = testQuestions[widget.testType] ?? [];
  }

  void _answerQuestion(int value) {
    setState(() {
      score += value;
      if (currentIndex < questions.length - 1) {
        currentIndex++;
      } else {
        _finishTest();
      }
    });
  }

Future<void> _finishTest() async {
  final now = DateTime.now().toIso8601String();
  await TestHistoryDB.insertResult(widget.testType, score, now);

  InterstitialAdHelper.showAd(
    onAdClosed: () {
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (ctx) => AlertDialog(
          title: const Text("Tes Selesai"),
          content: Text(
            "Skor kamu: $score dari ${questions.length}\n\nHasil ini disimpan ke riwayat tes.",
            style: GoogleFonts.nunito(fontSize: 16),
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.pop(ctx);
                Navigator.pop(context);
              },
              child: const Text("OK"),
            ),
          ],
        ),
      );
    },
  );
}


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFCAE7FF),
      appBar: AppBar(
        title: Text(
          widget.testLabel,
          style: GoogleFonts.nunito(
            color: Colors.black,
            fontWeight: FontWeight.bold,
          ),
        ),
        backgroundColor: const Color(0xFFCAE7FF),
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.black),
      ),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              LinearProgressIndicator(
                value: (currentIndex + 1) / questions.length,
                minHeight: 6,
                color: Colors.blueAccent,
                backgroundColor: Colors.grey.shade300,
              ),
              const SizedBox(height: 30),
              Text(
                "Pertanyaan ${currentIndex + 1}/${questions.length}",
                style: GoogleFonts.nunito(
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 10),
              Text(
                questions[currentIndex],
                textAlign: TextAlign.center,
                style: GoogleFonts.nunito(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 30),
              _buildAnswerButton("Tidak Pernah", 0),
              _buildAnswerButton("Kadang-kadang", 1),
              _buildAnswerButton("Sering", 2),
              _buildAnswerButton("Sangat Sering", 3),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildAnswerButton(String text, int value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: ElevatedButton(
        style: ElevatedButton.styleFrom(
          backgroundColor: Colors.blueAccent,
          minimumSize: const Size(double.infinity, 48),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
        onPressed: () => _answerQuestion(value),
        child: Text(
          text,
          style: GoogleFonts.nunito(
            fontSize: 16,
            color: Colors.white,
          ),
        ),
      ),
    );
  }
}
