import 'package:project/provider/shop_provider.dart';

final List<Bahan> semuaBahanList = [
  Bahan(
    nama: 'Tomat',
    harga: 3000,
    tersedia: true,
    gambar: 'img-project/tomat.jpg',
    satuan: 'per kg',
    kategori: 'Vegetable',
    jumlahPembelian :15,
  ),
  Bahan(
    nama: 'Daging Ayam',
    harga: 15000,
    tersedia: false,
    gambar: 'img-project/Ayam.jpg',
    satuan: 'per ekor',
    kategori: 'Meat',
    jumlahPembelian :30,
  ),
  Bahan(
    nama: 'Bayam',
    harga: 2000,
    tersedia: false,
    gambar: 'img-project/bayam.jpg',
    satuan: 'per ikat',
    kategori: 'Vegetable',
    jumlahPembelian :25,
  ),
  Bahan(
    nama: 'Oyster/tiram',
    harga: 23000,
    tersedia: true,
    gambar: 'img-project/oyster.jpeg',
    satuan: 'per kilo',
    kategori: 'Meat',
    jumlahPembelian :25,
  ),
  Bahan(
    nama: 'Wortel',
    harga: 4000,
    tersedia: true,
    gambar: 'img-project/wortel.jpg',
    satuan: 'per kg',
    kategori: 'Vegetable',
    jumlahPembelian :15,
  ),
  Bahan(
    nama: 'Brokoli',
    harga: 6000,
    tersedia: true,
    gambar: 'img-project/brokoli.jpeg',
    satuan: 'per kg',
    kategori: 'Vegetable',
    jumlahPembelian :20,
  ),

  Bahan(
    nama: 'Bacon-pork',
    harga: 27000,
    tersedia: false,
    gambar: 'img-project/bacon.jpeg',
    satuan: 'per kilo',
    kategori: 'Meat',
    jumlahPembelian :45,
  ),
  Bahan(
    nama: 'Daging Angsa',
    harga: 12000,
    tersedia: true,
    gambar: 'img-project/duck.jpeg',
    satuan: 'per ekor',
    kategori: 'Meat',
    jumlahPembelian :10,
  ),
  Bahan(
    nama: 'Ubi Jalar',
    harga: 18000,
    tersedia: true,
    gambar: 'img-project/ubi_jalar.jpeg',
    satuan: 'per kg',
    kategori: 'Vegetable',
    jumlahPembelian :25,
  ),
  Bahan(
    nama: 'Wagyu',
    harga: 340000,
    tersedia: true,
    gambar: 'img-project/wagyu.jpeg',
    satuan: 'per kilo',
    kategori: 'Meat',
    jumlahPembelian :45,
  ),
  Bahan(
    nama: 'telur',
    harga: 2000,
    tersedia: true,
    gambar: 'img-project/telur.jpeg',
    satuan: 'per buah',
    kategori: 'Meat',
    jumlahPembelian :55,
  ),
  Bahan(
    nama: 'Minyak kelapa murni/vco',
    harga: 8000,
    tersedia: true,
    gambar: 'img-project/vco.jpeg',
    satuan: 'per botol',
    kategori: 'Vegetable',
    jumlahPembelian :15,
  ),
  Bahan(
    nama: 'Lobster',
    harga: 120000,
    tersedia: true,
    gambar: 'img-project/lobster.jpeg',
    satuan: 'per ekor',
    kategori: 'Meat',
    jumlahPembelian :23,
  ),
  Bahan(
    nama: 'Pak Choy',
    harga: 15000,
    tersedia: true,
    gambar: 'img-project/pak_choy.jpeg',
    satuan: 'per ikat',
    kategori: 'Vegetable',
    jumlahPembelian :25,
  ),
  Bahan(
    nama: 'Kailan',
    harga: 12000,
    tersedia: true,
    gambar: 'img-project/kailan.jpeg',
    satuan: 'per ikat',
    kategori: 'Vegetable',
    jumlahPembelian :24,
  ),
  Bahan(
    nama: 'Kacang Almond',
    harga: 17000,
    tersedia: true,
    gambar: 'img-project/kacang_almond.jpeg',
    satuan: 'per bungkus',
    kategori: 'Vegetable',
    jumlahPembelian :35,
  ),
  Bahan(
    nama: 'Daun Ketumbar',
    harga: 18000,
    tersedia: true,
    gambar: 'img-project/ubi_jalar.jpeg',
    satuan: 'per kg',
    kategori: 'Vegetable',
    jumlahPembelian :15,
  ),
  Bahan(
    nama: 'Salmon fillet',
    harga: 336000,
    tersedia: false,
    gambar: 'img-project/salmon.jpeg',
    satuan: 'per kilo',
    kategori: 'Meat',
    jumlahPembelian :45,
  ),
  Bahan(
    nama: 'Dada ayam',
    harga: 24000,
    tersedia: true,
    gambar: 'img-project/chicken_breast.jpeg',
    satuan: 'per kilo',
    kategori: 'Meat',
    jumlahPembelian :55,
  ),
  Bahan(
    nama: 'Daging Bison',
    harga: 29000,
    tersedia: true,
    gambar: 'img-project/Bison_meat.jpeg',
    satuan: 'per kilo',
    kategori: 'Meat',
    jumlahPembelian :15,
  ),
  Bahan(
    nama: 'Kubis Ungu',
    harga: 8000,
    tersedia: true,
    gambar: 'img-project/kubis_ungu.jpeg',
    satuan: 'per kilo',
    kategori: 'Vegetable',
    jumlahPembelian :15,
  ),
];
